### ISSUE TITLE
Storing Population Objects

### ISSUE THREAD

**Issue by beratyenilen** [beratyenilen/qc-ga#8]
We need to figure out a way to store population objects so that we can analyse our results at a later time easily.
- One possible way to do this is using pickle library.
- Other is storing circuits as strings, parsing them, and initializing a population that way.

Tom could have a look at the Statistics part of DEAP, logbook, that may be useful.

**Comment by oskarTom** [comment]
Pickling seems to be quite straightforward:

Writing:
```python
import pickle

f = open("./output/output_pop", "wb")
pickle.dump(pop, f)
f.close()
```

And reading:
```python
import pickle

f = open("input_pop", "rb")
pop = pickle.load(f)
f.close()
```

**Comment by oskarTom** [comment]
Population objects are just lists with candidate objects, right? Pickling these seemed to be quite straightforward.

Writing:
```python
import pickle

f = open("./outputs/populations/output_pop", "wb")
pickle.dump(pop, f)
f.close()
```

Reading:
```python
f = open("input_pop", "rb")
pop = pickle.load(f)
f.close()
```

Please let me know if this wasn't what you were looking for
